# Generated by Django 4.2.4 on 2023-08-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='type_of_muscle',
            new_name='muscle_name',
        ),
        migrations.CreateModel(
            name='Workoutplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, default='', max_length=255)),
                ('muscle_name', models.CharField(blank=True, default='', max_length=255)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=255)),
                ('sets', models.CharField(blank=True, default='', max_length=255)),
                ('reps', models.CharField(blank=True, default='', max_length=255)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workouts')),
            ],
        ),
    ]
