# Generated by Django 4.2.4 on 2023-08-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workouts_rename_type_of_muscle_exercise_muscle_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workoutplan',
        ),
        migrations.DeleteModel(
            name='Workouts',
        ),
    ]
