# Generated by Django 4.2.4 on 2023-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_workoutplan_delete_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
