# Generated by Django 4.2.4 on 2023-08-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workoutplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, default='', max_length=255)),
                ('muscle_name', models.CharField(blank=True, default='', max_length=255)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=255)),
                ('sets', models.CharField(blank=True, default='', max_length=255)),
                ('reps', models.CharField(blank=True, default='', max_length=255)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workouts')),
            ],
        ),
    ]
