# Generated by Django 4.2.4 on 2023-08-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workoutplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
