# Generated by Django 4.2.4 on 2023-09-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=255)),
                ('muscle_name', models.CharField(max_length=255)),
                ('exercise_name', models.CharField(max_length=255)),
                ('sets', models.CharField(max_length=255)),
                ('reps', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, default='', max_length=255)),
                ('muscle_name', models.CharField(blank=True, default='', max_length=255)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=255)),
                ('sets', models.CharField(blank=True, default='', max_length=255)),
                ('reps', models.CharField(blank=True, default='', max_length=255)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_lists', to='base.workoutlist')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('set_count', models.IntegerField()),
                ('rep_count', models.IntegerField()),
                ('note', models.TextField()),
                ('work_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workoutlist')),
                ('work_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workoutstructure')),
            ],
        ),
    ]
