# Generated by Django 4.2.4 on 2023-08-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlist',
            name='workout_struc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.workoutstructure'),
        ),
        migrations.AlterField(
            model_name='workoutstructure',
            name='workout_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_lists', to='base.workoutlist'),
        ),
    ]
