# Generated by Django 4.2.4 on 2023-08-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workouts',
            new_name='WorkoutList',
        ),
    ]
