# Generated by Django 4.2.4 on 2023-08-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_workouts_workoutlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPlan',
            new_name='WorkoutStructure',
        ),
    ]
