# Generated by Django 4.2.4 on 2023-08-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_workoutlist_workout_struc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlist',
            name='workout_struc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.workoutstructure', unique=True),
        ),
    ]
