# Generated by Django 4.2.4 on 2023-09-14 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_exercise_options_alter_workoutlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='weight',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
            preserve_default=False,
        ),
    ]
