# Generated by Django 4.2.4 on 2023-09-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_progressimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='base/images')),
                ('workout_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workoutlist')),
            ],
        ),
    ]
